# Generated by Django 3.1.7 on 2021-04-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxType', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('filerType', models.CharField(max_length=30)),
                ('rangeMax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rangeRate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
