# Generated by Django 3.1.7 on 2021-04-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_auto_20210407_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbracket',
            name='rangeRate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
